ARG OPENSUSE_VERSION=42.3

FROM opensuse:${OPENSUSE_VERSION}

ARG TF_VERSION="1.4.1"
ARG PY_VERSION_SUFFIX=""

RUN zypper install -y \
    python{PY_VERSION_SUFFIX} \
    python{PY_VERSION_SUFFIX}-pip

# Upgrade pip and setuptools, because ubuntu 14 may have a very old version.
RUN pip${PY_VERSION_SUFFIX} install --upgrade \
    pip \
    setuptools

RUN pip${PY_VERSION_SUFFIX} install tensorflow==${TF_VERSION}
