ARG CENTOS_VERSION=7

FROM centos:${CENTOS_VERSION}

ARG TF_VERSION="1.4.1"

# Python is already installed on centos base image.
# Just need to install pip
RUN curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" && \
    python get-pip.py


RUN pip install tensorflow==${TF_VERSION}
